# Generated by Django 3.1 on 2021-07-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rack', '0002_rack_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('ending_slot', models.IntegerField()),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
                ('item_AC', models.CharField(max_length=50)),
                ('item_DC', models.CharField(max_length=50)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rack.rack')),
            ],
        ),
    ]
