# Generated by Django 3.1 on 2021-07-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rack', '0001_initial'),
        ('rows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='rows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rows.rows'),
        ),
    ]
